"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "quizly"
compatibility_date = "2026-04-25"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = true
preview_urls = false
upload_source_maps = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_AUTH_MODE = "production"
NEXT_PUBLIC_ENABLE_DEV_AUTH_SHORTCUT = "false"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "quizly"

[env.staging]
name = "quizly"
workers_dev = true
preview_urls = true
upload_source_maps = true

[env.staging.assets]
directory = ".open-next/assets"
binding = "ASSETS"

[env.staging.vars]
NEXT_PUBLIC_SITE_URL = "https://quizly.stdy.workers.dev"
NEXT_PUBLIC_AUTH_MODE = "production"
NEXT_PUBLIC_ENABLE_DEV_AUTH_SHORTCUT = "false"

[[env.staging.services]]
binding = "WORKER_SELF_REFERENCE"
service = "quizly"
